### ISSUE TITLE
Teste

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#10]
```yaml
start_date: 2022/02/09
due_date: 2022/02/18
progress: 0
parent: 0
```
