### ISSUE TITLE
Fazer aquela coisa

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#11]
```yaml
start_date: 2022/02/09
due_date: 2022/02/18
progress: 0
parent: 0
```

Aquela tarefa
