### ISSUE TITLE
Teste

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#12]
```yaml
start_date: 2022/02/10
due_date: 2022/02/10
progress: 0
parent: 0
```
