### ISSUE TITLE
Adicionar tela de criar/editar issue

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#14]
```yaml
start_date: 2022/02/10
due_date: 2022/02/11
progress: 0
parent: 0
```
