### ISSUE TITLE
Melhorada performance do scroll vertical quando possui muitos registros

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#15]
```yaml
start_date: 2022/02/08
due_date: 2022/02/10
progress: 0
parent: 0
```
