### ISSUE TITLE
Implementada deleção de tarefas selecionadas

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#16]
```yaml
start_date: 2022/02/11
due_date: 2022/02/12
progress: 0
parent: 0
```
