### ISSUE TITLE
Implementada inversão de estado das tarefas selecionadas

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#17]
```yaml
start_date: 2022/02/12
due_date: 2022/02/12
progress: 0
parent: 0
```
