### ISSUE TITLE
Melhorar experiência de aumento do período exibido no gráfico

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#18]
```yaml
start_date: 2023/03/30 00:00:00
due_date: 2023/04/03 00:00:00
progress: 0
parent: 
```
