### ISSUE TITLE
Implementada exibição de limites de uso da API do github

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#19]
```yaml
start_date: 2022/02/14
due_date: 2022/02/15
progress: 0
parent: 
```
