### ISSUE TITLE
Corrigida divisória voltando para a posição padrão após usar botão direito no gráfico

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#20]
```yaml
start_date: 2022/02/14
due_date: 2022/02/14
progress: 0
parent: 0
```
