### ISSUE TITLE
Corrigida dispensa da janela de criação de tarefas

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#21]
```yaml
start_date: 2022/02/15
due_date: 2022/02/15
progress: 0
parent: 0
```
