### ISSUE TITLE
Corrigido tamanho dos diálogos de seleção de responsáveis e labels

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#22]
```yaml
start_date: 2022/02/15
due_date: 2022/02/15
progress: 0
parent: 0
```
