### ISSUE TITLE
Corrigido alinhamento horizontal dos responsáveis

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#23]
```yaml
start_date: 2022/02/15
due_date: 2022/02/15
progress: 0
parent: 0
```
