### ISSUE TITLE
Implementar setas para indicação de dependências

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#24]
```yaml
start_date: 2022/03/02 00:00:00
due_date: 2022/03/03 00:00:00
progress: 0
parent: 
```
