### ISSUE TITLE
Criar script de CI/CD

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#25]
```yaml
start_date: 2022/02/16
due_date: 2022/02/17
progress: 0
parent: 0
```
