### ISSUE TITLE
Implementada compilação para windows

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#26]
```yaml
start_date: 2022/02/08
due_date: 2022/02/09
progress: 0
parent: 0
```
