### ISSUE TITLE
Adicionado texto da versão na interface e na compilação

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#27]
```yaml
start_date: 2022/02/16
due_date: 2022/02/16
progress: 0
parent: 0
```
