### ISSUE TITLE
Criado diagrama de classes do projeto

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#28]
```yaml
start_date: 2022/03/02
due_date: 2022/03/02
progress: 0
parent: 
```
