### ISSUE TITLE
Teste

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#30]
```yaml
start_date: 2022/03/02
due_date: 2022/03/02
progress: 0
parent: 
```
