### ISSUE TITLE
Feito com que a posição vertical e horizontal do gráfico seja restaurada para melhor experiência

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#33]
```yaml
start_date: 2022/03/02
due_date: 2022/03/02
progress: 0
parent: 
```
