### ISSUE TITLE
Corrigida falha ao abrir tela de sobre quando conexão com API não foi estabelecida

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#37]
```yaml
start_date: 2023/04/02 00:00:00
due_date: 2023/04/03 00:00:00
progress: 0
parent: 
```
