### ISSUE TITLE
Tornar a aplicação responsiva

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#38]
```yaml
start_date: 2022/03/06
due_date: 2022/03/06
progress: 0
parent: 
```
