### ISSUE TITLE
Teste

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#39]
```yaml
start_date: 2022/03/03
due_date: 2022/03/03
progress: 0
parent: 
```
