### ISSUE TITLE
Correção ao editar tarefa logo após editar

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#42]
```yaml
start_date: 2022/03/06
due_date: 2022/03/06
progress: 0
parent: 
```

Era como se as alterações não tivessem sido aplicadas
