### ISSUE TITLE
Melhorado posicionamento do repositório e do token

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#43]
```yaml
start_date: 2022/03/06
due_date: 2022/03/06
progress: 0
parent: 
```
