### ISSUE TITLE
Implementado movimento de pinça no celular para aumentar ou diminuir a largura dos dias

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#44]
```yaml
start_date: 2022/03/06
due_date: 2022/03/06
progress: 0
parent: 
```
