### ISSUE TITLE
Implementada alternativa ao botão direito em dispositivos móveis

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#45]
```yaml
start_date: 2022/03/06
due_date: 2022/03/06
progress: 0
parent: 
```

Usado o toque longo
