### ISSUE TITLE
Feito com que o gráfico vá até a tarefa ao selecioná-la

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#48]
```yaml
start_date: 2023/05/29 00:00:00
due_date: 2023/05/29 02:00:00
progress: 0
parent: 
```
