### ISSUE TITLE
Adicionadas configurações relacionadas a dias a semana não trabalhados, horas não trabalhadas, dias específicos não trabalhados e valor por hora de trabalho

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#51]
```yaml
start_date: 2023/05/23 20:00:00
due_date: 2023/05/24 20:00:00
progress: 0
parent: 
```
