### ISSUE TITLE
Adicionada classe para logs no terminal

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#52]
```yaml
start_date: 2022/04/02 00:00:00
due_date: 2022/04/03 00:00:00
progress: 0
parent: 
```
