### ISSUE TITLE
Refatorada algumas partes do código

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#53]
```yaml
start_date: 2023/05/24 20:00:00
due_date: 2023/05/25 00:00:00
progress: 0
parent: 
```
