### ISSUE TITLE
Trocado de login do usuário para login do dono do repositório nas urls do github

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#56]
```yaml
start_date: 2023/05/23 20:00:00
due_date: 2023/05/23 22:00:00
progress: 0
parent: 
```
