### ISSUE TITLE
Corrigidos erros na leitura de algumas issues

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#57]
```yaml
start_date: 2023/05/23 22:00:00
due_date: 2023/05/24 00:00:00
progress: 0
parent: 
```
