### ISSUE TITLE
Feito com que seja atualizado o body, a hora inicial e final após atualização da issue

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#58]
```yaml
start_date: 2023/05/24 18:00:00
due_date: 2023/05/24 20:00:00
progress: 0
parent: 
```
