### ISSUE TITLE
Adicionado campo de valor na classe de issue

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#59]
```yaml
start_date: 2023/05/24 20:00:00
due_date: 2023/05/24 22:00:00
progress: 0
parent: 
```
