### ISSUE TITLE
Renomeados alguns arquivos

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#60]
```yaml
start_date: 2022/04/02 00:00:00
due_date: 2022/04/03 00:00:00
progress: 0
parent: 
```
