### ISSUE TITLE
Melhorada performance de rolagem do gráfico e das tarefas

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#61]
```yaml
start_date: 2023/05/25 00:00:00
due_date: 2023/05/27 00:00:00
progress: 0
parent: 
```
