### ISSUE TITLE
Corrigida falha a abrir tela Sobre em alguns casos

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#62]
```yaml
start_date: 2023/05/23 18:00:00
due_date: 2023/05/23 20:00:00
progress: 0
parent: 
```
