### ISSUE TITLE
Adicionados valores por tarefa e total do projeto

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#63]
```yaml
start_date: 2023/05/27 00:00:00
due_date: 2023/05/28 00:00:00
progress: 0
parent: 
```
