### ISSUE TITLE
Adicionadas horas trabalhadas e totais por tarefa, além do total do de horas trabalhadas e totais do projeto

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#64]
```yaml
start_date: 2023/05/27 00:00:00
due_date: 2023/05/28 00:00:00
progress: 0
parent: 
```
