### ISSUE TITLE
Removida obscuridade do filtro

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#66]
```yaml
start_date: 2023/05/28 00:00:00
due_date: 2023/05/28 20:00:00
progress: 0
parent: 
```
