### ISSUE TITLE
Adicionada compilação para linux

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#67]
```yaml
start_date: 2023/05/28 18:00:00
due_date: 2023/05/28 20:00:00
progress: 0
parent: 
```
