### ISSUE TITLE
Feito com que a lista de tarefas e o gráfico não percam a posição após criar uma nova tarefa

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#68]
```yaml
start_date: 2023/05/30 20:00:00
due_date: 2023/05/30 22:00:00
progress: 0
parent: 
```
