### ISSUE TITLE
Corrigida impossibilidade de múltipla seleção de tarefa após usar o filtro

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#69]
```yaml
start_date: 2023/05/29 20:00:00
due_date: 2023/05/31 12:00:00
progress: 0
parent: 
```
