### ISSUE TITLE
Implementada seleção de múltiplos repositórios

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#70]
```yaml
start_date: 2023/05/30 22:00:00
due_date: 2023/06/02 00:00:00
progress: 0
parent: 
```

Para visualizar terefas de mais de um ao mesmo tempo
