### ISSUE TITLE
Aplicada cores de estado na fonte, e não mais no continer da tarefa

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#71]
```yaml
start_date: 2023/06/02 00:00:00
due_date: 2023/06/03 00:00:00
progress: 0
parent: 
```
