### ISSUE TITLE
Feito com qe seja possível escolher a cor de cada repositório, sendo inicialmente todos cinzas, essas cores serão aplicadas aos containeres das tarefas

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#72]
```yaml
start_date: 2023/06/02 00:00:00
due_date: 2023/06/04 14:00:00
progress: 0
parent: 
```
