### ISSUE TITLE
Feito com que o gráfico seja inciado exibindo a data atual

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#73]
```yaml
start_date: 2023/05/31 22:00:00
due_date: 2023/06/01 00:00:00
progress: 0
parent: 
```
