### ISSUE TITLE
Corrigida atualização de título da tarefa

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#74]
```yaml
start_date: 2023/05/30 20:00:00
due_date: 2023/05/30 22:00:00
progress: 0
parent: 
```
