### ISSUE TITLE
Corrigido resultado do redirecionamento de rotas do Github

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#79]
```yaml
start_date: 2023/06/09 22:00:00
due_date: 2023/06/10 00:00:00
progress: 0
parent: 
```
