### ISSUE TITLE
Corrigido carregamento de milestones, labels, e responsáveis ao criar tarefas

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/flutter_github_gantt#80]
```yaml
start_date: 2023/06/09 22:00:00
due_date: 2023/06/10 00:00:00
progress: 0
parent: 
```
